#ifndef SIMPLE_MATTER_H
#define SIMPLE_MATTER_H

/* Generated by scripts/gen-cffi-header.sh (cbindgen). DO NOT EDIT. */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

// 期限なしのセンチネル([`sm_next_deadline`] が返す。C 側 `SM_NO_DEADLINE`)。
#define SM_NO_DEADLINE UINT64_MAX

// 追加できるカスタムクラスタの最大数。
#define MAX_CUSTOM_CLUSTERS 8

// 追加できる新規エンドポイントの最大数。
#define MAX_CUSTOM_ENDPOINTS 4

// 1 クラスタあたりの属性上限。
#define MAX_ATTRS 16

// 1 クラスタあたりのコマンド上限。
#define MAX_CMDS 8

// invoke の引数(context tag)上限。
#define MAX_ARGS 8

// 文字列/オクテット列の上限バイト数(`sm_attr_value_t` 内固定バッファ)。
#define STR_CAP 64

// 書き込み可能(未指定は read-only)。
#define SM_ATTR_WRITABLE (1 << 0)

// NULLABLE(null 許容)。
#define SM_ATTR_NULLABLE (1 << 1)

// timed write 必須。
#define SM_ATTR_TIMED (1 << 2)

// timed invoke 必須。
#define SM_CMD_TIMED (1 << 0)

// 属性/引数のスカラ型タグ(§8.1)。
typedef enum {
  SM_T_BOOL = 0,
  SM_T_U8,
  SM_T_U16,
  SM_T_U32,
  SM_T_U64,
  SM_T_I8,
  SM_T_I16,
  SM_T_I32,
  SM_T_I64,
  SM_T_F32,
  SM_T_STRING,
  SM_T_OCTETS,
} sm_attr_type_t;

// BLE(BTP)イベント種別(`sm_ble_event` の引数、`docs/design/c-ffi-shim.md` §9.1)。
typedef enum {
  // GATT 接続確立。`arg` = ATT MTU(不明なら 0 = 23 扱い)。
  SM_BLE_CONNECTED = 0,
  // GATT 切断。
  SM_BLE_DISCONNECTED = 1,
  // C1(0xFFF6 write)受信。`data`/`len` = 書き込まれた 1 BTP フラグメント。
  SM_BLE_C1_WRITE = 2,
  // C2(indicate)CCCD subscribe 完了。以降 `sm_ble_poll` のフラグメントを送出可。
  SM_BLE_C2_SUBSCRIBED = 3,
} sm_ble_event_kind_t;

// アプリイベント種別(`docs/design/c-ffi-shim.md` §1)。
typedef enum {
  SM_EV_NONE = 0,
  SM_EV_ONOFF_CHANGED = 1,
  SM_EV_COMMISSIONED = 2,
  SM_EV_FABRIC_REMOVED = 3,
  SM_EV_WINDOW_CHANGED = 4,
  // BLE commissionable 広告の内容が変わった(`sm_ble_adv_data` を再取得して反映。§9.1)。
  SM_EV_BLE_ADV_CHANGED = 5,
  // ConnectNetwork 受理で WiFi join 要求が立った(`sm_take_wifi_request` で取り出す。§9.1)。
  SM_EV_WIFI_CONNECT_REQUEST = 6,
  // ConnectNetwork 受理で Thread attach 要求が立った(`sm_take_thread_dataset` で
  // dataset TLV を取り出す。§10.1)。
  SM_EV_THREAD_ATTACH_REQUEST = 7,
} sm_event_kind_t;

// プリセット NetworkCommissioning の種別(`docs/design/c-ffi-shim.md` §10.1)。
//
// C 側が `sm_config_t` を 0 クリアすると `SM_NET_ETHERNET`(従来動作)になる(後方互換)。
// WiFi / Thread は BLE コミッショニング前提のため、ble 無効ビルドでは種別によらず
// Ethernet として動作する。
typedef enum {
  // Ethernet(FeatureMap EN)。既定・後方互換。
  SM_NET_ETHERNET = 0,
  // WiFi(FeatureMap WI)。`pairing ble-wifi`。ble 必須。
  SM_NET_WIFI = 1,
  // Thread(FeatureMap TH)。`pairing ble-thread`。ble 必須。
  SM_NET_THREAD = 2,
} sm_network_t;

// KVS get コールバック: 値を `buf` へ書き実長を返す(無ければ負値)。
typedef int32_t (*SmKvsGet)(void *ctx, const char *key, uint8_t *buf, size_t cap);

// KVS set コールバック。
typedef int32_t (*SmKvsSet)(void *ctx, const char *key, const uint8_t *val, size_t len);

// KVS delete コールバック(冪等)。
typedef int32_t (*SmKvsDelete)(void *ctx, const char *key);

// RNG コールバック(esp_fill_random 等)。
typedef void (*SmRngFill)(void *ctx, uint8_t *buf, size_t len);

// 初期化設定(`docs/design/c-ffi-shim.md` §1)。
typedef struct {
  // discriminator(12 ビット)。
  uint16_t discriminator;
  // PASE パスコード(開発用)。
  uint32_t passcode;
  // Vendor ID(commissionable 広告に反映)。
  uint16_t vendor_id;
  // Product ID(commissionable 広告に反映)。
  uint16_t product_id;
  // mDNS インスタンス名の素材(NULL 可、現状 device_name TXT は固定値)。
  const char *device_name;
  // hostname / instance id 用の MAC。
  uint8_t mac[6];
  // KVS get コールバック(NULL 可 = 永続化なし)。
  SmKvsGet kvs_get;
  // KVS set コールバック。
  SmKvsSet kvs_set;
  // KVS delete コールバック。
  SmKvsDelete kvs_delete;
  // KVS コールバックの ctx。
  void *kvs_ctx;
  // RNG コールバック(必須)。
  SmRngFill rng_fill;
  // RNG コールバックの ctx。
  void *rng_ctx;
  // プリセット NetworkCommissioning の種別(0 = SM_NET_ETHERNET = 従来動作。§10.1)。
  sm_network_t network;
} sm_config_t;

// v4/v6 両対応の datagram 宛先/送信元。
typedef struct {
  // IP アドレス(v4 は先頭 4 バイト)。
  uint8_t ip[16];
  // v6 なら true。
  bool is_v6;
  // ポート。
  uint16_t port;
  // v6 link-local 用 scope_id(それ以外 0)。
  uint32_t scope_id;
} sm_addr_t;

// アプリイベント(立った順にリングから取り出す)。
typedef struct {
  sm_event_kind_t kind;
  // 補助値(ONOFF: 0/1、COMMISSIONED/FABRIC_REMOVED: fabric 数、WINDOW: 0=閉/1=開)。
  uint8_t arg;
} sm_event_t;

// 属性定義(§8.1)。
typedef struct {
  // 属性 ID。
  uint32_t attr_id;
  // スカラ型。
  sm_attr_type_t type;
  // `SM_ATTR_*` フラグ。
  uint32_t flags;
} sm_attr_def_t;

// コマンド定義(§8.1)。
typedef struct {
  // コマンド ID。
  uint32_t cmd_id;
  // `SM_CMD_*` フラグ。
  uint32_t flags;
} sm_cmd_def_t;

// 短いバイト列/文字列(64B 上限。§8.2)。
typedef struct {
  // バイト内容(STRING は UTF-8、末尾 NUL 不要)。
  uint8_t buf[STR_CAP];
  // 有効バイト数。
  uint8_t len;
} sm_attr_bytes;

// スカラ + 短いバイト列の tagged union の値部(§8.1)。
typedef union {
  // 真偽値。
  bool b;
  // 符号なし整数。
  uint64_t u;
  // 符号付き整数。
  int64_t i;
  // 単精度浮動小数点数。
  float f;
  // 文字列/オクテット列。
  sm_attr_bytes bytes;
} sm_attr_value_data;

// スカラ + 短いバイト列の tagged union(§8.1)。
typedef struct {
  // 値の型。
  sm_attr_type_t type;
  // NULLABLE 属性のみ有効(true = null)。
  bool is_null;
  // 値本体(`type` で解釈)。
  sm_attr_value_data v;
} sm_attr_value_t;

// read コールバック(値を `out` へ。戻り値 = IM ステータス、0=Success)。
typedef uint8_t (*SmClusterRead)(void *ctx, uint32_t attr_id, sm_attr_value_t *out);

// write コールバック(戻り値 = IM ステータス)。
typedef uint8_t (*SmClusterWrite)(void *ctx, uint32_t attr_id, const sm_attr_value_t *val);

// invoke コールバック(引数はスカラ列に平坦化。戻り値 = IM ステータス)。
typedef uint8_t (*SmClusterInvoke)(void *ctx, uint32_t cmd_id, const sm_attr_value_t *args, size_t n_args, uint64_t now_ms);

// カスタムクラスタ定義(§8.1)。`attrs`/`cmds` は登録時にシムがコピーする。
typedef struct {
  // 追加先エンドポイント(新規 EP は 2..、プリセット EP1 への追加も可)。
  uint16_t endpoint;
  // クラスタ ID(vendor 領域 or 標準 ID)。
  uint32_t cluster_id;
  // クラスタリビジョン。
  uint16_t revision;
  // FeatureMap。
  uint32_t feature_map;
  // 属性定義配列。
  const sm_attr_def_t *attrs;
  // 属性定義数。
  size_t n_attrs;
  // コマンド定義配列。
  const sm_cmd_def_t *cmds;
  // コマンド定義数。
  size_t n_cmds;
  // read ハンドラ。
  SmClusterRead read;
  // write ハンドラ。
  SmClusterWrite write;
  // invoke ハンドラ。
  SmClusterInvoke invoke;
  // コールバック ctx。
  void *ctx;
} sm_cluster_def_t;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// スタックを初期化する(KVS から fabric/ACL/resumption 復元込み)。0=OK、負値=失敗。
int32_t sm_init(const sm_config_t *cfg,
                uint64_t now_ms);

// Matter UDP(:5540)受信。戻り値 = tx_out に書いた応答長(0 = 応答なし)。
size_t sm_udp_rx(uint8_t *datagram,
                 size_t len,
                 const sm_addr_t *src,
                 uint64_t now_ms,
                 uint8_t *tx_out,
                 size_t tx_cap,
                 sm_addr_t *tx_dst);

// 期限処理(MRP 再送・ACK・購読レポート)。0 になるまで繰り返し呼んで送信する。
size_t sm_poll(uint64_t now_ms,
               uint8_t *tx_out,
               size_t tx_cap,
               sm_addr_t *tx_dst);

// 次に sm_poll を呼ぶべき時刻(ms)。SM_NO_DEADLINE(=UINT64_MAX)= 期限なし。
uint64_t sm_next_deadline(uint64_t now_ms);

// DHCP 後のアドレス反映(A/AAAA 更新)。NULL は「未設定」。
void sm_set_addrs(const uint8_t *ipv4, const uint8_t *ipv6_ll);

// mDNS(:5353)受信応答。戻り値 = tx_out に書いた応答長、tx_dst に宛先(QU=ユニキャスト)。
size_t sm_mdns_rx(const uint8_t *pkt,
                  size_t len,
                  const sm_addr_t *src,
                  uint8_t *tx_out,
                  size_t tx_cap,
                  sm_addr_t *tx_dst);

// mDNS の定期 announce。戻り値 = tx_out に書いた長さ、tx_dst にマルチキャスト宛先。
size_t sm_mdns_poll(uint64_t now_ms,
                    uint8_t *tx_out,
                    size_t tx_cap,
                    sm_addr_t *tx_dst);

// アプリイベントを立った順に 1 件取り出す(LED 反映等)。
bool sm_take_event(sm_event_t *out);

// ローカル操作の OnOff 書き戻し(物理スイッチ等)。
void sm_onoff_set(bool on, uint64_t now_ms);

// 現在の OnOff 状態。
bool sm_onoff_get(void);

// コミッション済み fabric 数。
uint8_t sm_fabric_count(void);

// カスタムクラスタを登録する(sm_init より前。0=OK、負値=失敗)。
//
// `def`/`attrs`/`cmds` の内容はここでコピーするため、呼び出し後は解放してよい
// (コールバックポインタ・ctx は保持されるので有効に保つこと)。sm_init 済みは `-2`。
int32_t sm_cluster_register(const sm_cluster_def_t *def);

// 新規エンドポイント(2..)にデバイスタイプを付与して登録する(sm_init より前)。
//
// プリセット EP0/EP1(0/1)は登録不可(`-5`)。sm_init 済みは `-2`。
int32_t sm_endpoint_register(uint16_t endpoint,
                             uint32_t device_type,
                             uint8_t dt_revision);

// C 側の値変化を購読レポートへ橋渡しする(該当カスタムクラスタを dirty にする)。
void sm_attr_mark_dirty(uint16_t endpoint,
                        uint32_t cluster_id,
                        uint32_t attr_id);

// BLE(BTP)イベントをシムへ給餌する(§9.1)。0=OK、負値=エラー。
//
// - `SM_BLE_CONNECTED`(`arg`=ATT MTU、0=不明): 2 本目の接続は `-2`(C++ は切断すべき)。
// - `SM_BLE_C1_WRITE`(`data`/`len`=1 上りフラグメント): BTP に投入し、再組立できた
//   Matter メッセージを処理して応答を BTP に積む(送出は `sm_ble_poll`)。
// - `SM_BLE_C2_SUBSCRIBED` / `SM_BLE_DISCONNECTED`: セッション状態を更新。
//
// ble 無効ビルドは常に `-1`。
int32_t sm_ble_event(sm_ble_event_kind_t kind,
                     uint16_t arg,
                     const uint8_t *data,
                     size_t len,
                     uint64_t now_ms);

// C2 indication で送るべき次の BTP フラグメントを取り出す(§9.1)。0 = なし。
//
// subscribe 完了前・未接続は 0(handshake 応答も subscribe 後に排出する)。BTP の
// 再送・keep-alive ACK もここから産まれる(`sm_next_deadline` が BTP 期限を併合する)。
// ble 無効ビルドは常に 0。
size_t sm_ble_poll(uint64_t now_ms,
                   uint8_t *frag_out,
                   size_t cap);

// commissionable 広告(Flags AD + Service Data 0xFFF6、計 15 バイト)を `out` に書く(§9.1)。
//
// 戻り値 = 書いた長さ。0 = 広告を停止すべき状態(fabric あり・窓閉)。内容が変わると
// `SM_EV_BLE_ADV_CHANGED` が立つので、C++ はそれを受けて本 API を再取得し NimBLE に反映する。
// ble 無効ビルドは常に 0。
size_t sm_ble_adv_data(uint8_t *out,
                       size_t cap);

// ConnectNetwork で受理した WiFi join 要求(SSID/資格情報)を取り出す(§9.1)。
//
// 戻り値 = SSID バイト長(0 = 保留要求なし)。`pass_len` に資格情報長を返す。
// `SM_EV_WIFI_CONNECT_REQUEST` を受けて呼ぶ。取り出したら C++ が esp_wifi で join し、
// 結果を [`sm_wifi_status`] で報告する。ble 無効ビルドは常に 0。
size_t sm_take_wifi_request(uint8_t *ssid_out,
                            size_t ssid_cap,
                            uint8_t *pass_out,
                            size_t pass_cap,
                            size_t *pass_len);

// WiFi join 結果を報告する(§9.1)。遅延 ConnectNetworkResponse がこれで確定する。
//
// `connected`=true で Connected、false で Failed。次の `sm_poll`/`sm_ble_poll` サイクルで
// コアが遅延 ConnectNetworkResponse を BTP に積む。ble 無効ビルドは no-op。
void sm_wifi_status(bool connected,
                    uint64_t now_ms);

// ConnectNetwork で受理した Thread attach 要求の dataset TLV を取り出す(§10.1)。
//
// 戻り値 = dataset TLV バイト長(0 = 保留要求なし / Thread 構成でない / ble 無効)。
// `SM_EV_THREAD_ATTACH_REQUEST` を受けて呼ぶ。取り出したら C++ が esp_openthread へ
// `otDatasetSetActiveTlvs` で投入し Thread start → attach を開始し、結果を
// [`sm_thread_status`] で報告する。
size_t sm_take_thread_dataset(uint8_t *tlv_out,
                              size_t cap);

// Thread attach 結果を報告する(§10.1)。遅延 ConnectNetworkResponse がこれで確定する。
//
// `attached`=true で Attached、false で Failed。次の `sm_poll`/`sm_ble_poll` サイクルで
// コアが遅延 ConnectNetworkResponse を BTP に積む。Thread 構成でない / ble 無効は no-op。
void sm_thread_status(bool attached,
                      uint64_t now_ms);

// SRP の運用インスタンス名素材 `<compressedFabricId>-<nodeId>`(各 16 進大文字 16 桁)を
// `buf` へ NUL 終端で書く(`docs/design/c-ffi-shim.md` §10.1)。
//
// 戻り値 = NUL を除く名前長(33)。fabric 未確定 / `cap` 不足(< 34)は 0。fabric 複数時は
// 最初の 1 つを使う(制約: マルチ fabric では代表 1 つのみ。§10.1)。
size_t sm_operational_instance_name(uint8_t *buf,
                                    size_t cap);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus

#endif /* SIMPLE_MATTER_H */
