#ifndef SIMPLE_MATTER_H
#define SIMPLE_MATTER_H

/* Generated by scripts/gen-cffi-header.sh (cbindgen). DO NOT EDIT. */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

// 期限なしのセンチネル([`sm_next_deadline`] が返す。C 側 `SM_NO_DEADLINE`)。
#define SM_NO_DEADLINE UINT64_MAX

// アプリイベント種別(`docs/design/c-ffi-shim.md` §1)。
typedef enum {
  SM_EV_NONE = 0,
  SM_EV_ONOFF_CHANGED = 1,
  SM_EV_COMMISSIONED = 2,
  SM_EV_FABRIC_REMOVED = 3,
  SM_EV_WINDOW_CHANGED = 4,
} sm_event_kind_t;

// KVS get コールバック: 値を `buf` へ書き実長を返す(無ければ負値)。
typedef int32_t (*SmKvsGet)(void *ctx, const char *key, uint8_t *buf, size_t cap);

// KVS set コールバック。
typedef int32_t (*SmKvsSet)(void *ctx, const char *key, const uint8_t *val, size_t len);

// KVS delete コールバック(冪等)。
typedef int32_t (*SmKvsDelete)(void *ctx, const char *key);

// RNG コールバック(esp_fill_random 等)。
typedef void (*SmRngFill)(void *ctx, uint8_t *buf, size_t len);

// 初期化設定(`docs/design/c-ffi-shim.md` §1)。
typedef struct {
  // discriminator(12 ビット)。
  uint16_t discriminator;
  // PASE パスコード(開発用)。
  uint32_t passcode;
  // Vendor ID(commissionable 広告に反映)。
  uint16_t vendor_id;
  // Product ID(commissionable 広告に反映)。
  uint16_t product_id;
  // mDNS インスタンス名の素材(NULL 可、現状 device_name TXT は固定値)。
  const char *device_name;
  // hostname / instance id 用の MAC。
  uint8_t mac[6];
  // KVS get コールバック(NULL 可 = 永続化なし)。
  SmKvsGet kvs_get;
  // KVS set コールバック。
  SmKvsSet kvs_set;
  // KVS delete コールバック。
  SmKvsDelete kvs_delete;
  // KVS コールバックの ctx。
  void *kvs_ctx;
  // RNG コールバック(必須)。
  SmRngFill rng_fill;
  // RNG コールバックの ctx。
  void *rng_ctx;
} sm_config_t;

// v4/v6 両対応の datagram 宛先/送信元。
typedef struct {
  // IP アドレス(v4 は先頭 4 バイト)。
  uint8_t ip[16];
  // v6 なら true。
  bool is_v6;
  // ポート。
  uint16_t port;
  // v6 link-local 用 scope_id(それ以外 0)。
  uint32_t scope_id;
} sm_addr_t;

// アプリイベント(立った順にリングから取り出す)。
typedef struct {
  sm_event_kind_t kind;
  // 補助値(ONOFF: 0/1、COMMISSIONED/FABRIC_REMOVED: fabric 数、WINDOW: 0=閉/1=開)。
  uint8_t arg;
} sm_event_t;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// スタックを初期化する(KVS から fabric/ACL/resumption 復元込み)。0=OK、負値=失敗。
int32_t sm_init(const sm_config_t *cfg,
                uint64_t now_ms);

// Matter UDP(:5540)受信。戻り値 = tx_out に書いた応答長(0 = 応答なし)。
size_t sm_udp_rx(uint8_t *datagram,
                 size_t len,
                 const sm_addr_t *src,
                 uint64_t now_ms,
                 uint8_t *tx_out,
                 size_t tx_cap,
                 sm_addr_t *tx_dst);

// 期限処理(MRP 再送・ACK・購読レポート)。0 になるまで繰り返し呼んで送信する。
size_t sm_poll(uint64_t now_ms,
               uint8_t *tx_out,
               size_t tx_cap,
               sm_addr_t *tx_dst);

// 次に sm_poll を呼ぶべき時刻(ms)。SM_NO_DEADLINE(=UINT64_MAX)= 期限なし。
uint64_t sm_next_deadline(uint64_t now_ms);

// DHCP 後のアドレス反映(A/AAAA 更新)。NULL は「未設定」。
void sm_set_addrs(const uint8_t *ipv4, const uint8_t *ipv6_ll);

// mDNS(:5353)受信応答。戻り値 = tx_out に書いた応答長、tx_dst に宛先(QU=ユニキャスト)。
size_t sm_mdns_rx(const uint8_t *pkt,
                  size_t len,
                  const sm_addr_t *src,
                  uint8_t *tx_out,
                  size_t tx_cap,
                  sm_addr_t *tx_dst);

// mDNS の定期 announce。戻り値 = tx_out に書いた長さ、tx_dst にマルチキャスト宛先。
size_t sm_mdns_poll(uint64_t now_ms,
                    uint8_t *tx_out,
                    size_t tx_cap,
                    sm_addr_t *tx_dst);

// アプリイベントを立った順に 1 件取り出す(LED 反映等)。
bool sm_take_event(sm_event_t *out);

// ローカル操作の OnOff 書き戻し(物理スイッチ等)。
void sm_onoff_set(bool on, uint64_t now_ms);

// 現在の OnOff 状態。
bool sm_onoff_get(void);

// コミッション済み fabric 数。
uint8_t sm_fabric_count(void);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus

#endif /* SIMPLE_MATTER_H */
