#ifndef SIMPLE_MATTER_H
#define SIMPLE_MATTER_H

/* Generated by scripts/gen-cffi-header.sh (cbindgen). DO NOT EDIT. */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

// 期限なしのセンチネル([`sm_next_deadline`] が返す。C 側 `SM_NO_DEADLINE`)。
#define SM_NO_DEADLINE UINT64_MAX

// 追加できるカスタムクラスタの最大数。
#define MAX_CUSTOM_CLUSTERS 8

// 追加できる新規エンドポイントの最大数。
#define MAX_CUSTOM_ENDPOINTS 4

// 1 クラスタあたりの属性上限。
#define MAX_ATTRS 16

// 1 クラスタあたりのコマンド上限。
#define MAX_CMDS 8

// invoke の引数(context tag)上限。
#define MAX_ARGS 8

// 文字列/オクテット列の上限バイト数(`sm_attr_value_t` 内固定バッファ)。
#define STR_CAP 64

// 書き込み可能(未指定は read-only)。
#define SM_ATTR_WRITABLE (1 << 0)

// NULLABLE(null 許容)。
#define SM_ATTR_NULLABLE (1 << 1)

// timed write 必須。
#define SM_ATTR_TIMED (1 << 2)

// timed invoke 必須。
#define SM_CMD_TIMED (1 << 0)

// 属性/引数のスカラ型タグ(§8.1)。
typedef enum {
  SM_T_BOOL = 0,
  SM_T_U8,
  SM_T_U16,
  SM_T_U32,
  SM_T_U64,
  SM_T_I8,
  SM_T_I16,
  SM_T_I32,
  SM_T_I64,
  SM_T_F32,
  SM_T_STRING,
  SM_T_OCTETS,
} sm_attr_type_t;

// BLE(BTP)イベント種別(`sm_ble_event` の引数、`docs/design/c-ffi-shim.md` §9.1)。
typedef enum {
  // GATT 接続確立。`arg` = ATT MTU(不明なら 0 = 23 扱い)。
  SM_BLE_CONNECTED = 0,
  // GATT 切断。
  SM_BLE_DISCONNECTED = 1,
  // C1(0xFFF6 write)受信。`data`/`len` = 書き込まれた 1 BTP フラグメント。
  SM_BLE_C1_WRITE = 2,
  // C2(indicate)CCCD subscribe 完了。以降 `sm_ble_poll` のフラグメントを送出可。
  SM_BLE_C2_SUBSCRIBED = 3,
} sm_ble_event_kind_t;

// コントローライベント種別(`sm_ctrl_take_event` で取り出す)。
typedef enum {
  // イベント無し(ABI ゼロ値のセンチネル)。
  SM_CTRL_EV_NONE = 0,
  // コミッショニングのフェーズが進んだ(`phase` = フェーズコード。§11.1)。
  SM_CTRL_EV_PAIR_PHASE = 1,
  // コミッショニング完了(`node_id` = 対象ノード)。以降 invoke/read 可。
  SM_CTRL_EV_PAIR_COMPLETE = 2,
  // コミッショニング失敗(`phase` = 失敗フェーズコード)。
  SM_CTRL_EV_PAIR_FAILED = 3,
  // 運用 CASE セッションを確立した(`node_id`、`resumed` = Sigma2Resume 経由か)。
  SM_CTRL_EV_CASE_ESTABLISHED = 4,
  // 運用 CASE 確立に失敗した(`node_id`)。
  SM_CTRL_EV_CASE_FAILED = 5,
  // Invoke 完了(`node_id`、`status` = IM ステータス。0 = 成功)。
  SM_CTRL_EV_INVOKE_DONE = 6,
  // Invoke 失敗(`node_id`、`status`)。
  SM_CTRL_EV_INVOKE_FAILED = 7,
  // Read 完了(`node_id`、`value_u64` / `value_is_null` にスカラ値)。
  SM_CTRL_EV_READ_DONE = 8,
  // Read 失敗(`node_id`)。
  SM_CTRL_EV_READ_FAILED = 9,
  // operational 解決成功(`node_id`。アドレスは `sm_ctrl_node_addr` で取得)。
  SM_CTRL_EV_RESOLVE_DONE = 10,
  // BLE コミッショニングフェーズ完了(§11.4)。`node_id` = 対象ノード。
  //
  // AddNOC + ネットワーク資格情報投入 + ConnectNetwork まで BTP 上で完了した。C++ は
  // BLE を切断(`sm_ctrl_ble_event(DISCONNECTED)`)し、運用アドレスを解決
  // ([`sm_ctrl_resolve_start`] / [`sm_ctrl_mdns_rx`])してから運用 UDP で pump を回す
  // (CASE → CommissioningComplete → PAIR_COMPLETE。ble-commissioner `--udp-handoff` の流儀)。
  SM_CTRL_EV_BLE_DONE = 11,
  // Write 完了(`node_id`、`status` = IM ステータス。0 = 成功)。
  SM_CTRL_EV_WRITE_DONE = 12,
  // Write 失敗(`node_id`、`status`)。
  SM_CTRL_EV_WRITE_FAILED = 13,
  // Subscribe のプライミングが完了した(`node_id`、`value_u64` = 購読 ID)。
  SM_CTRL_EV_SUBSCRIBE_DONE = 14,
  // Subscribe 開始に失敗した(`node_id`)。
  SM_CTRL_EV_SUBSCRIBE_FAILED = 15,
  // 購読レポートを受理した(§16.2)。`node_id` + `endpoint` / `cluster` / `attribute` が
  // 対象パス、`value_u64` / `value_is_null` が最新スカラ値。1 通のレポートに複数属性が
  // 載っていれば **属性ごとに 1 イベント**。`phase` = 購読 ID 下位 8bit(診断用)。
  SM_CTRL_EV_REPORT = 16,
  // 購読が失われた(keep-alive 途絶。§16.2)。`node_id`、`value_u64` = 購読 ID。
  // シムの購読テーブルからは除去済みなので、C++ 側は poll フォールバック / 再購読へ。
  SM_CTRL_EV_SUBSCRIPTION_LOST = 17,
  // コミッショニング窓を開いた(§17.3)。`node_id` = 対象ノード、`value_u64` = 払い出した
  // passcode、`endpoint` = discriminator、`attribute` = timeout(秒)。manual pairing code /
  // QR 文字列込みの全情報は [`sm_ctrl_last_window`] で取る。
  SM_CTRL_EV_WINDOW_OPENED = 18,
  // コミッショニング窓を開けなかった(§17.3)。`status` = クラスタ固有ステータス
  // (Busy=2 / PAKEParameterError=3)または IM ステータス、`phase` = 失敗段階
  // (1=VendorID read、2=ProductID read、3=OpenCommissioningWindow invoke。
  // 0xE0/0xD0/0xF0 台は診断コード)。
  SM_CTRL_EV_WINDOW_FAILED = 19,
} sm_ctrl_event_kind_t;

// アプリイベント種別(`docs/design/c-ffi-shim.md` §1)。
typedef enum {
  SM_EV_NONE = 0,
  SM_EV_ONOFF_CHANGED = 1,
  SM_EV_COMMISSIONED = 2,
  SM_EV_FABRIC_REMOVED = 3,
  SM_EV_WINDOW_CHANGED = 4,
  // BLE commissionable 広告の内容が変わった(`sm_ble_adv_data` を再取得して反映。§9.1)。
  SM_EV_BLE_ADV_CHANGED = 5,
  // ConnectNetwork 受理で WiFi join 要求が立った(`sm_take_wifi_request` で取り出す。§9.1)。
  SM_EV_WIFI_CONNECT_REQUEST = 6,
  // ConnectNetwork 受理で Thread attach 要求が立った(`sm_take_thread_dataset` で
  // dataset TLV を取り出す。§10.1)。
  SM_EV_THREAD_ATTACH_REQUEST = 7,
} sm_event_kind_t;

// プリセット NetworkCommissioning の種別(`docs/design/c-ffi-shim.md` §10.1)。
//
// C 側が `sm_config_t` を 0 クリアすると `SM_NET_ETHERNET`(従来動作)になる(後方互換)。
// WiFi / Thread は BLE コミッショニング前提のため、ble 無効ビルドでは種別によらず
// Ethernet として動作する。
typedef enum {
  // Ethernet(FeatureMap EN)。既定・後方互換。
  SM_NET_ETHERNET = 0,
  // WiFi(FeatureMap WI)。`pairing ble-wifi`。ble 必須。
  SM_NET_WIFI = 1,
  // Thread(FeatureMap TH)。`pairing ble-thread`。ble 必須。
  SM_NET_THREAD = 2,
} sm_network_t;

// KVS get コールバック: 値を `buf` へ書き実長を返す(無ければ負値)。
typedef int32_t (*SmKvsGet)(void *ctx, const char *key, uint8_t *buf, size_t cap);

// KVS set コールバック。
typedef int32_t (*SmKvsSet)(void *ctx, const char *key, const uint8_t *val, size_t len);

// KVS delete コールバック(冪等)。
typedef int32_t (*SmKvsDelete)(void *ctx, const char *key);

// RNG コールバック(esp_fill_random 等)。
typedef void (*SmRngFill)(void *ctx, uint8_t *buf, size_t len);

// DAC 秘密鍵署名コールバック(セキュアエレメント委譲用)。
//
// `msg`(`msg_len` バイト)に ECDSA-SHA256 署名し、生 `r||s`(64 バイト)を `out` に書く。
// 0 = 成功、負値 = 失敗。`sm_config_t::dac_privkey` の代わりに使う。
typedef int32_t (*SmDacSign)(void *ctx, const uint8_t *msg, size_t msg_len, uint8_t *out);

// 短いバイト列/文字列(64B 上限。§8.2)。
typedef struct {
  // バイト内容(STRING は UTF-8、末尾 NUL 不要)。
  uint8_t buf[STR_CAP];
  // 有効バイト数。
  uint8_t len;
} sm_attr_bytes;

// スカラ + 短いバイト列の tagged union の値部(§8.1)。
typedef union {
  // 真偽値。
  bool b;
  // 符号なし整数。
  uint64_t u;
  // 符号付き整数。
  int64_t i;
  // 単精度浮動小数点数。
  float f;
  // 文字列/オクテット列。
  sm_attr_bytes bytes;
} sm_attr_value_data;

// スカラ + 短いバイト列の tagged union(§8.1)。
typedef struct {
  // 値の型。
  sm_attr_type_t type;
  // NULLABLE 属性のみ有効(true = null)。
  bool is_null;
  // 値本体(`type` で解釈)。
  sm_attr_value_data v;
} sm_attr_value_t;

// 属性値変化コールバック(composition モードの汎用フック。§9.1)。
//
// IM write / コマンドでクラスタの状態が変わると、変化した属性ごとに 1 回呼ばれる。
typedef void (*SmClusterChange)(void *ctx, uint16_t endpoint, uint32_t cluster_id, uint32_t attr_id, const sm_attr_value_t *value);

// 初期化設定(`docs/design/c-ffi-shim.md` §1)。
typedef struct {
  // discriminator(12 ビット)。
  uint16_t discriminator;
  // [非推奨・開発専用] PASE パスコード。**デバイスは passcode を保持してはならない**
  // (Matter セキュリティ要件)。後方互換のため残すが、製品では `verifier_w0_l` /
  // `verifier_salt` / `verifier_iterations` で SPAKE2+ verifier を直接渡すこと。
  // verifier(`verifier_w0_l` 非 NULL かつ `verifier_iterations != 0`)が指定された場合、
  // 本フィールドは無視される。
  uint32_t passcode;
  // Vendor ID(commissionable 広告に反映)。
  uint16_t vendor_id;
  // Product ID(commissionable 広告に反映)。
  uint16_t product_id;
  // mDNS インスタンス名の素材(NULL 可、現状 device_name TXT は固定値)。
  const char *device_name;
  // hostname / instance id 用の MAC。
  uint8_t mac[6];
  // KVS get コールバック(NULL 可 = 永続化なし)。
  SmKvsGet kvs_get;
  // KVS set コールバック。
  SmKvsSet kvs_set;
  // KVS delete コールバック。
  SmKvsDelete kvs_delete;
  // KVS コールバックの ctx。
  void *kvs_ctx;
  // RNG コールバック(必須)。
  SmRngFill rng_fill;
  // RNG コールバックの ctx。
  void *rng_ctx;
  // プリセット NetworkCommissioning の種別(0 = SM_NET_ETHERNET = 従来動作。§10.1)。
  sm_network_t network;
  // SPAKE2+ verifier の iteration count。0 = 未指定(`passcode` からの導出にフォールバック)。
  // verifier を使う場合は `verifier_w0_l` と併せて非 0 を設定する。
  uint32_t verifier_iterations;
  // SPAKE2+ verifier の salt(16..=32 バイト)。NULL の場合は既定 dev salt を使う。
  const uint8_t *verifier_salt;
  // `verifier_salt` の長さ(バイト)。
  size_t verifier_salt_len;
  // SPAKE2+ verifier 本体 `w0 ‖ L`(97 バイト)。NULL のとき、または
  // `verifier_iterations == 0` のときは `passcode` から導出する(開発専用フォールバック)。
  // **推奨: 製品はここに verifier を渡し、passcode をデバイスに置かない**
  // (`smctl pase-verifier <passcode>` で生成)。
  const uint8_t *verifier_w0_l;
  // DAC 証明書(X.509 DER)。`pai_der` / `cd_der` と、`dac_privkey` または
  // `dac_sign` のいずれかが揃ったときに [`BorrowedDacProvider`] を使う。
  // いずれかが欠ければ従来の dev テスト DAC(`TestDacProvider`)にフォールバック。
  const uint8_t *dac_der;
  // `dac_der` の長さ(バイト、≤ 1024)。
  size_t dac_der_len;
  // PAI 証明書(X.509 DER)。
  const uint8_t *pai_der;
  // `pai_der` の長さ(バイト、≤ 1024)。
  size_t pai_der_len;
  // Certification Declaration(CMS DER)。
  const uint8_t *cd_der;
  // `cd_der` の長さ(バイト、≤ 1024)。
  size_t cd_der_len;
  // DAC 生秘密鍵(P-256 スカラ 32 バイト、ビッグエンディアン)。NULL なら `dac_sign` を使う。
  const uint8_t *dac_privkey;
  // DAC 署名コールバック(セキュアエレメント委譲)。`dac_privkey` が NULL のとき使う。
  SmDacSign dac_sign;
  // `dac_sign` の ctx。
  void *dac_sign_ctx;
  // エンドポイント構成 blob(Matter TLV)。**NULL = 従来の固定 OnOff ライト構成**
  // (EP1 = Identify/Groups/OnOff/Descriptor。既存 example と完全互換)。
  //
  // 非 NULL のときは EP1 以降を blob の宣言どおりに合成する(EP0 のシステムクラスタは
  // 固定)。スキーマは `crate::compose` のモジュールドキュメント。パース失敗は
  // `sm_init` が `-7`、容量超過/未対応クラスタは `-8` を返す。
  const uint8_t *composition;
  // `composition` の長さ(バイト)。
  size_t composition_len;
  // 属性値が IM write / コマンドで変化したときのコールバック(NULL 可)。
  //
  // 合成クラスタ(および従来構成の EP1 OnOff)の監視対象属性が変化すると発火する。
  // `sm_attr_set_value` による**アプリ発の変化では発火しない**(HAL のループを避けるため)。
  SmClusterChange on_cluster_change;
  // `on_cluster_change` の ctx。
  void *cluster_change_ctx;
} sm_config_t;

// v4/v6 両対応の datagram 宛先/送信元。
typedef struct {
  // IP アドレス(v4 は先頭 4 バイト)。
  uint8_t ip[16];
  // v6 なら true。
  bool is_v6;
  // ポート。
  uint16_t port;
  // v6 link-local 用 scope_id(それ以外 0)。
  uint32_t scope_id;
} sm_addr_t;

// 各プールの使用量([`sm_pool_stats`])。C 側 `sm_pool_stats_t` と同レイアウト。
typedef struct {
  // exchange 会話数 / 容量。
  uint16_t exchanges;
  uint16_t exchanges_cap;
  // セッション数(平文・予約含む)/ 容量。
  uint16_t sessions;
  uint16_t sessions_cap;
  // 進行中ハンドシェイク数 / 容量。
  uint16_t handshakes;
  uint16_t handshakes_cap;
  // 使用中の再送バッファ数 / 容量。
  uint16_t tx_bufs;
  uint16_t tx_bufs_cap;
  // 購読数 / 容量(設計 §16.6 診断。幽霊購読で SUBS が詰まる兆候を見る)。
  uint16_t subs;
  uint16_t subs_cap;
  // 進行中の Read / プライミング継続 slot 数 / 容量。
  uint16_t reads;
  uint16_t reads_cap;
} sm_pool_stats_t;

// アプリイベント(立った順にリングから取り出す)。
typedef struct {
  sm_event_kind_t kind;
  // 補助値(ONOFF: 0/1、COMMISSIONED/FABRIC_REMOVED: fabric 数、WINDOW: 0=閉/1=開)。
  uint8_t arg;
} sm_event_t;

// 属性定義(§8.1)。
typedef struct {
  // 属性 ID。
  uint32_t attr_id;
  // スカラ型。
  sm_attr_type_t type;
  // `SM_ATTR_*` フラグ。
  uint32_t flags;
} sm_attr_def_t;

// コマンド定義(§8.1)。
typedef struct {
  // コマンド ID。
  uint32_t cmd_id;
  // `SM_CMD_*` フラグ。
  uint32_t flags;
} sm_cmd_def_t;

// read コールバック(値を `out` へ。戻り値 = IM ステータス、0=Success)。
typedef uint8_t (*SmClusterRead)(void *ctx, uint32_t attr_id, sm_attr_value_t *out);

// write コールバック(戻り値 = IM ステータス)。
typedef uint8_t (*SmClusterWrite)(void *ctx, uint32_t attr_id, const sm_attr_value_t *val);

// invoke コールバック(引数はスカラ列に平坦化。戻り値 = IM ステータス)。
typedef uint8_t (*SmClusterInvoke)(void *ctx, uint32_t cmd_id, const sm_attr_value_t *args, size_t n_args, uint64_t now_ms);

// カスタムクラスタ定義(§8.1)。`attrs`/`cmds` は登録時にシムがコピーする。
typedef struct {
  // 追加先エンドポイント(新規 EP は 2..、プリセット EP1 への追加も可)。
  uint16_t endpoint;
  // クラスタ ID(vendor 領域 or 標準 ID)。
  uint32_t cluster_id;
  // クラスタリビジョン。
  uint16_t revision;
  // FeatureMap。
  uint32_t feature_map;
  // 属性定義配列。
  const sm_attr_def_t *attrs;
  // 属性定義数。
  size_t n_attrs;
  // コマンド定義配列。
  const sm_cmd_def_t *cmds;
  // コマンド定義数。
  size_t n_cmds;
  // read ハンドラ。
  SmClusterRead read;
  // write ハンドラ。
  SmClusterWrite write;
  // invoke ハンドラ。
  SmClusterInvoke invoke;
  // コールバック ctx。
  void *ctx;
} sm_cluster_def_t;

// コントローラ初期化設定(`docs/design/c-ffi-shim.md` §11.1)。
typedef struct {
  // コントローラ fabric の FabricId(smctl / examples と同値を推奨。例 0xFAB0000000000001)。
  // KVS に ca-state があればそちらが優先され、本値は無視される。
  uint64_t fabric_id;
  // コントローラ自身の運用 NodeId(CaseAdminSubject / CASE identity)。同上。
  uint64_t controller_node_id;
  // AdminVendorId(AddNOC に載せる)。
  uint16_t vendor_id;
  // KVS get コールバック(NULL 可 = 永続化なし。`b"cast"`/`b"nods"`/`b"rsm*"` を委譲)。
  SmKvsGet kvs_get;
  // KVS set コールバック。
  SmKvsSet kvs_set;
  // KVS delete コールバック(冪等)。
  SmKvsDelete kvs_delete;
  // KVS コールバックの ctx。
  void *kvs_ctx;
  // RNG コールバック(必須。esp_fill_random / getrandom 等)。
  SmRngFill rng_fill;
  // RNG コールバックの ctx。
  void *rng_ctx;
} sm_ctrl_config_t;

// コントローライベント(立った順にリングから取り出す)。
typedef struct {
  // 種別。
  sm_ctrl_event_kind_t kind;
  // コミッショニングのフェーズコード(PAIR_PHASE / PAIR_FAILED)。
  // 0=Idle 1=PASE 2=ArmFailSafe 3=Attestation 4=CSR 5=AddTrustedRoot 6=AddNOC
  // 7=CASE 8=Complete 9=Done 10=AddWiFi 11=ConnectNetwork。
  uint8_t phase;
  // IM/SC ステータスコード(INVOKE/READ 系。0 = 成功)。
  uint8_t status;
  // 対象ノードの運用 NodeId。
  uint64_t node_id;
  // Read スカラ値(READ_DONE。符号付きは 2 の補数ビットパターン)。
  uint64_t value_u64;
  // Read 値が null(READ_DONE)。
  bool value_is_null;
  // CASE が resumption(Sigma2Resume)経由で確立したか(CASE_ESTABLISHED)。
  bool resumed;
  // 対象パスのエンドポイント(REPORT のみ有効。§16.2)。
  uint16_t endpoint;
  // 対象パスのクラスタ(REPORT のみ有効)。
  uint32_t cluster;
  // 対象パスの属性(REPORT のみ有効)。
  uint32_t attribute;
} sm_ctrl_event_t;

// 購読する属性パス 1 本(`sm_ctrl_subscribe_paths` の引数。§16.2)。
typedef struct {
  // エンドポイント ID。
  uint16_t endpoint;
  // クラスタ ID。
  uint32_t cluster;
  // 属性 ID。
  uint32_t attribute;
} sm_attr_path_t;

// 直近に開いたコミッショニング窓の払い出し情報(§17.3)。
//
// [`sm_ctrl_open_commissioning_window`] が成功したあと [`sm_ctrl_last_window`] で取る。
// `manual_code` / `qr_payload` はどちらも NUL 終端の ASCII。
typedef struct {
  // 窓を開けた相手ノードの運用 NodeId。
  uint64_t node_id;
  // 窓を開けておく秒数(OpenCommissioningWindow に渡した値)。
  uint16_t timeout_s;
  // 窓の 12 ビット discriminator。
  uint16_t discriminator;
  // 払い出した setup passcode。
  uint32_t passcode;
  // QR 用 VendorID(read できなければ 0)。
  uint16_t vendor_id;
  // QR 用 ProductID(read できなければ 0)。
  uint16_t product_id;
  // 11 桁 manual pairing code + NUL。
  char manual_code[12];
  // `"MT:"` + base38 の QR payload + NUL。
  char qr_payload[32];
  // 窓を開いた時刻(呼び出し側の `now_ms`)。0 = 未オープン。
  uint64_t opened_at_ms;
} sm_ctrl_window_t;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// スタックを初期化する(KVS から fabric/ACL/resumption 復元込み)。0=OK、負値=失敗。
int32_t sm_init(const sm_config_t *cfg,
                uint64_t now_ms);

// Matter UDP(:5540)受信。戻り値 = tx_out に書いた応答長(0 = 応答なし)。
size_t sm_udp_rx(uint8_t *datagram,
                 size_t len,
                 const sm_addr_t *src,
                 uint64_t now_ms,
                 uint8_t *tx_out,
                 size_t tx_cap,
                 sm_addr_t *tx_dst);

// 期限処理(MRP 再送・ACK・購読レポート)。0 になるまで繰り返し呼んで送信する。
size_t sm_poll(uint64_t now_ms,
               uint8_t *tx_out,
               size_t tx_cap,
               sm_addr_t *tx_dst);

// コアの各プール使用量を `out` に書く(診断用。未初期化・NULL は 0 埋め)。
//
// 実機で「受信はするが応答しない」枯渇状態(exchange / セッション / handshake slot)を
// ログから見分けるための足場(2026-08-25 NanoC6 調査)。
void sm_pool_stats(sm_pool_stats_t *out);

// 次に sm_poll を呼ぶべき時刻(ms)。SM_NO_DEADLINE(=UINT64_MAX)= 期限なし。
uint64_t sm_next_deadline(uint64_t now_ms);

// DHCP 後のアドレス反映(A/AAAA 更新)。NULL は「未設定」。
void sm_set_addrs(const uint8_t *ipv4, const uint8_t *ipv6_ll);

// mDNS(:5353)受信応答。戻り値 = tx_out に書いた応答長、tx_dst に宛先(QU=ユニキャスト)。
size_t sm_mdns_rx(const uint8_t *pkt,
                  size_t len,
                  const sm_addr_t *src,
                  uint8_t *tx_out,
                  size_t tx_cap,
                  sm_addr_t *tx_dst);

// mDNS の定期 announce。戻り値 = tx_out に書いた長さ、tx_dst にマルチキャスト宛先。
size_t sm_mdns_poll(uint64_t now_ms,
                    uint8_t *tx_out,
                    size_t tx_cap,
                    sm_addr_t *tx_dst);

// アプリイベントを立った順に 1 件取り出す(LED 反映等)。
bool sm_take_event(sm_event_t *out);

// ローカル操作の OnOff 書き戻し(物理スイッチ等)。
//
// composition モードでは**最小 EP の OnOff クラスタ**が対象(無ければ no-op)。
void sm_onoff_set(bool on, uint64_t now_ms);

// 現在の OnOff 状態(composition モードは最小 EP の OnOff。無ければ false)。
bool sm_onoff_get(void);

// 属性値を書く(センサ値 push・ローカル操作の書き戻し)。
//
// 対象は composition で合成したクラスタ、従来構成の EP1 OnOff、および F4b の
// CustomCluster(登録された write ハンドラへ委譲)。書き込みは購読へ反映される
// (クラスタが dirty になる)が、`on_cluster_change` は**発火しない**
// (アプリ発の変化で HAL がループしないため)。
//
// 戻り値: 0=OK、-1=未初期化/NULL、-2=対象クラスタ無し、-3=属性が非対応、-4=型不一致。
int32_t sm_attr_set_value(uint16_t endpoint,
                          uint32_t cluster_id,
                          uint32_t attr_id,
                          const sm_attr_value_t *value);

// 属性値を読む(HAL / スクリプトからの状態取得)。
//
// 対象は [`sm_attr_set_value`] と同じ。戻り値の意味も同じ(-3 = 属性が非対応)。
int32_t sm_attr_get_value(uint16_t endpoint,
                          uint32_t cluster_id,
                          uint32_t attr_id,
                          sm_attr_value_t *out);

// コミッション済み fabric 数。
uint8_t sm_fabric_count(void);

// カスタムクラスタを登録する(sm_init より前。0=OK、負値=失敗)。
//
// `def`/`attrs`/`cmds` の内容はここでコピーするため、呼び出し後は解放してよい
// (コールバックポインタ・ctx は保持されるので有効に保つこと)。sm_init 済みは `-2`。
int32_t sm_cluster_register(const sm_cluster_def_t *def);

// 新規エンドポイント(2..)にデバイスタイプを付与して登録する(sm_init より前)。
//
// プリセット EP0/EP1(0/1)は登録不可(`-5`)。sm_init 済みは `-2`。
int32_t sm_endpoint_register(uint16_t endpoint,
                             uint32_t device_type,
                             uint8_t dt_revision);

// C 側の値変化を購読レポートへ橋渡しする(該当カスタムクラスタを dirty にする)。
void sm_attr_mark_dirty(uint16_t endpoint,
                        uint32_t cluster_id,
                        uint32_t attr_id);

// BLE(BTP)イベントをシムへ給餌する(§9.1)。0=OK、負値=エラー。
//
// - `SM_BLE_CONNECTED`(`arg`=ATT MTU、0=不明): 2 本目の接続は `-2`(C++ は切断すべき)。
// - `SM_BLE_C1_WRITE`(`data`/`len`=1 上りフラグメント): BTP に投入し、再組立できた
//   Matter メッセージを処理して応答を BTP に積む(送出は `sm_ble_poll`)。
// - `SM_BLE_C2_SUBSCRIBED` / `SM_BLE_DISCONNECTED`: セッション状態を更新。
//
// ble 無効ビルドは常に `-1`。
int32_t sm_ble_event(sm_ble_event_kind_t kind,
                     uint16_t arg,
                     const uint8_t *data,
                     size_t len,
                     uint64_t now_ms);

// C2 indication で送るべき次の BTP フラグメントを取り出す(§9.1)。0 = なし。
//
// subscribe 完了前・未接続は 0(handshake 応答も subscribe 後に排出する)。BTP の
// 再送・keep-alive ACK もここから産まれる(`sm_next_deadline` が BTP 期限を併合する)。
// ble 無効ビルドは常に 0。
size_t sm_ble_poll(uint64_t now_ms,
                   uint8_t *frag_out,
                   size_t cap);

// commissionable 広告(Flags AD + Service Data 0xFFF6、計 15 バイト)を `out` に書く(§9.1)。
//
// 戻り値 = 書いた長さ。0 = 広告を停止すべき状態(fabric あり・窓閉)。内容が変わると
// `SM_EV_BLE_ADV_CHANGED` が立つので、C++ はそれを受けて本 API を再取得し NimBLE に反映する。
// ble 無効ビルドは常に 0。
size_t sm_ble_adv_data(uint8_t *out,
                       size_t cap);

// ConnectNetwork で受理した WiFi join 要求(SSID/資格情報)を取り出す(§9.1)。
//
// 戻り値 = SSID バイト長(0 = 保留要求なし)。`pass_len` に資格情報長を返す。
// `SM_EV_WIFI_CONNECT_REQUEST` を受けて呼ぶ。取り出したら C++ が esp_wifi で join し、
// 結果を [`sm_wifi_status`] で報告する。ble 無効ビルドは常に 0。
size_t sm_take_wifi_request(uint8_t *ssid_out,
                            size_t ssid_cap,
                            uint8_t *pass_out,
                            size_t pass_cap,
                            size_t *pass_len);

// WiFi join 結果を報告する(§9.1)。遅延 ConnectNetworkResponse がこれで確定する。
//
// `connected`=true で Connected、false で Failed。次の `sm_poll`/`sm_ble_poll` サイクルで
// コアが遅延 ConnectNetworkResponse を BTP に積む。ble 無効ビルドは no-op。
void sm_wifi_status(bool connected,
                    uint64_t now_ms);

// ConnectNetwork で受理した Thread attach 要求の dataset TLV を取り出す(§10.1)。
//
// 戻り値 = dataset TLV バイト長(0 = 保留要求なし / Thread 構成でない / ble 無効)。
// `SM_EV_THREAD_ATTACH_REQUEST` を受けて呼ぶ。取り出したら C++ が esp_openthread へ
// `otDatasetSetActiveTlvs` で投入し Thread start → attach を開始し、結果を
// [`sm_thread_status`] で報告する。
size_t sm_take_thread_dataset(uint8_t *tlv_out,
                              size_t cap);

// Thread attach 結果を報告する(§10.1)。遅延 ConnectNetworkResponse がこれで確定する。
//
// `attached`=true で Attached、false で Failed。次の `sm_poll`/`sm_ble_poll` サイクルで
// コアが遅延 ConnectNetworkResponse を BTP に積む。Thread 構成でない / ble 無効は no-op。
void sm_thread_status(bool attached,
                      uint64_t now_ms);

// SRP の運用インスタンス名素材 `<compressedFabricId>-<nodeId>`(各 16 進大文字 16 桁)を
// `buf` へ NUL 終端で書く(`docs/design/c-ffi-shim.md` §10.1)。
//
// 戻り値 = NUL を除く名前長(33)。fabric 未確定 / `cap` 不足(< 34)は 0。fabric 複数時は
// 最初の 1 つを使う(制約: マルチ fabric では代表 1 つのみ。§10.1)。
size_t sm_operational_instance_name(uint8_t *buf,
                                    size_t cap);

// 供給メモリに構築する [`CtrlShim`] のバイトサイズ(`sm_ctrl_init` へ渡す `mem_len` の下限)。
size_t sm_ctrl_context_size(void);

// 供給メモリに要求するアラインメント(バイト)。`mem` はこの倍数でなければならない。
size_t sm_ctrl_context_align(void);

// コントローラを初期化する(供給メモリに in-place 構築 + KVS から CA/ノード帳/resumption 復元)。
//
// 戻り値: 0=OK、-1=NULL 引数、-2=既に初期化済み、-3=`mem_len` 不足、
// -4=`mem` アラインメント不正、-5=RNG コールバック未設定、-6=CA 生成失敗。
//
// `mem` は [`sm_ctrl_context_size`] バイト以上・[`sm_ctrl_context_align`] アラインで、
// [`sm_ctrl_deinit`] まで移動・解放しないこと(PSRAM 配置可)。
int32_t sm_ctrl_init(uint8_t *mem,
                     size_t mem_len,
                     const sm_ctrl_config_t *cfg,
                     uint64_t _now_ms);

// コントローラを破棄する(供給メモリの `CtrlShim` を drop。以降 `mem` は解放してよい)。
//
// 二重 init 防止フラグを解除する(同一プロセスでの再初期化 = プロセス再起動相当が可能になる)。
void sm_ctrl_deinit(void);

// コミッショニングを開始する(UDP 直接 PASE。§11.1)。
//
// 戻り値: 0=OK、-1=未初期化/NULL、-2=busy(他トランザクション進行中)、-3=commission 拒否。
// 進行は [`sm_ctrl_take_event`] の PAIR_PHASE / PAIR_COMPLETE / PAIR_FAILED で観測する。
int32_t sm_ctrl_pair_start(uint64_t node_id,
                           uint32_t passcode,
                           const sm_addr_t *addr,
                           uint64_t now_ms);

// Matter UDP 受信を処理する。戻り値 = tx_out に書いた送信長(0 = 送信なし)。
//
// C++ は 0 になるまで [`sm_ctrl_poll`] を続けて残りの送信を排出する。
size_t sm_ctrl_udp_rx(uint8_t *datagram,
                      size_t len,
                      const sm_addr_t *src,
                      uint64_t now_ms,
                      uint8_t *tx_out,
                      size_t tx_cap,
                      sm_addr_t *tx_dst);

// 時間駆動の送出を 1 件排出する(コミッショナ発行・MRP 再送・standalone ACK)。0 になるまで回す。
size_t sm_ctrl_poll(uint64_t now_ms,
                    uint8_t *tx_out,
                    size_t tx_cap,
                    sm_addr_t *tx_dst);

// 次に [`sm_ctrl_poll`] を呼ぶべき時刻(ms)。`SM_NO_DEADLINE` = 期限なし。
//
// TX キューに未排出があれば即時(`now_ms`)を返す。
uint64_t sm_ctrl_next_deadline(uint64_t now_ms);

// コントローライベントを立った順に 1 件取り出す。戻り値 = 取り出せたか。
bool sm_ctrl_take_event(sm_ctrl_event_t *out);

// 運用ノードへ引数なしコマンドを invoke する(OnOff Toggle 等の最小。§11.1)。
//
// live セッションが無ければ内部で CASE(resumption 可)を確立してから実行する。
// 完了は [`sm_ctrl_take_event`] の INVOKE_DONE / INVOKE_FAILED で観測する。
// 戻り値: 0=OK、-1=未初期化、-3=未知ノード、-4=CASE 開始失敗、-10=busy。
int32_t sm_ctrl_invoke(uint64_t node_id,
                       uint16_t endpoint,
                       uint32_t cluster,
                       uint32_t command,
                       uint64_t now_ms);

// 運用ノードのスカラ属性を read する(§11.1)。
//
// live セッションが無ければ内部で CASE を確立してから実行する。値は
// [`sm_ctrl_take_event`] の READ_DONE(`value_u64` / `value_is_null`)で返る。
// 戻り値: 0=OK、-1=未初期化、-3=未知ノード、-4=CASE 開始失敗、-10=busy。
int32_t sm_ctrl_read_scalar(uint64_t node_id,
                            uint16_t endpoint,
                            uint32_t cluster,
                            uint32_t attribute,
                            uint64_t now_ms);

// 引数付きコマンドを invoke する(LevelControl MoveToLevel 等。§11.1 の拡張)。
//
// `args` は context tag 0..`n_args`-1 の順に平坦化されたスカラ列
// ([`sm_attr_value_t`]。`sm_cluster_def_t` の invoke ハンドラと同じ表現)。`n_args` の
// 上限は 4。`args` が NULL / `n_args` = 0 なら [`sm_ctrl_invoke`] と等価。
// 完了は INVOKE_DONE / INVOKE_FAILED。
//
// 戻り値: 0=OK、-1=未初期化、-3=未知ノード、-4=CASE 開始失敗、-5=引数過多、-10=busy。
int32_t sm_ctrl_invoke_args(uint64_t node_id,
                            uint16_t endpoint,
                            uint32_t cluster,
                            uint32_t command,
                            const sm_attr_value_t *args,
                            size_t n_args,
                            uint64_t now_ms);

// 運用ノードのスカラ属性へ write する(§11.1 の拡張)。
//
// 完了は [`sm_ctrl_take_event`] の WRITE_DONE / WRITE_FAILED(`status` = IM ステータス)。
// 戻り値: 0=OK、-1=未初期化/NULL、-3=未知ノード、-4=CASE 開始失敗、-10=busy。
int32_t sm_ctrl_write_scalar(uint64_t node_id,
                             uint16_t endpoint,
                             uint32_t cluster,
                             uint32_t attribute,
                             const sm_attr_value_t *value,
                             uint64_t now_ms);

// 運用ノードのスカラ属性 1 本を subscribe する([`sm_ctrl_subscribe_paths`] の薄いラッパ)。
//
// 戻り値・イベントは [`sm_ctrl_subscribe_paths`] と同じ。
int32_t sm_ctrl_subscribe(uint64_t node_id,
                          uint16_t endpoint,
                          uint32_t cluster,
                          uint32_t attribute,
                          uint16_t min_interval_s,
                          uint16_t max_interval_s,
                          uint64_t now_ms);

// 運用ノードの複数属性を **1 本の購読**で subscribe する(§16.2)。
//
// プライミング完了で、まず含まれる属性ごとに SM_CTRL_EV_REPORT(`node_id` +
// `endpoint`/`cluster`/`attribute` + `value_u64`/`value_is_null`)、続いて
// SUBSCRIBE_DONE(`value_u64` = 購読 ID)。以降のデバイス発レポートも属性ごとに
// SM_CTRL_EV_REPORT。keep-alive 途絶で SM_CTRL_EV_SUBSCRIPTION_LOST。
//
// 同一ノードの既存購読があれば**先に捨てる**(二重購読しない)。購読テーブルは
// コアと同容量(4 ノード分)、1 購読あたりのパスは 8 本まで。
//
// 戻り値: 0=OK、-1=未初期化 / NULL、-3=未知ノード、-4=CASE 開始失敗、-10=busy、
// -11=パス数超過(0 本を含む)、-12=購読テーブル満杯。
int32_t sm_ctrl_subscribe_paths(uint64_t node_id,
                                const sm_attr_path_t *paths,
                                size_t n,
                                uint16_t min_interval_s,
                                uint16_t max_interval_s,
                                uint64_t now_ms);

// 既存 fabric の管理者として **ECM コミッショニング窓**を開く(§17.3)。
//
// `passcode` = 0 なら有効な setup passcode を乱数生成、`discriminator` = 0xFFFF なら
// 12 ビット discriminator を乱数生成する(それ以外は下位 12 ビットだけを使う)。
// `timeout_s` は仕様の許容範囲 180..=900 へクランプする。
//
// 内部で 3 段階を直列に進める:
// (1) EP0 BasicInformation VendorID(0x0002)read、(2) ProductID(0x0004)read
// (どちらも QR 用の飾りで、失敗しても VID/PID = 0 で続行)、
// (3) OpenCommissioningWindow(0x003C/0x00)を timed invoke。
//
// 完了は [`sm_ctrl_take_event`] の [`SM_CTRL_EV_WINDOW_OPENED`](`value_u64` = passcode、
// `endpoint` = discriminator、`attribute` = timeout 秒)/
// [`SM_CTRL_EV_WINDOW_FAILED`](`status` = ステータス、`phase` = 失敗段階)。
// manual pairing code / QR 文字列込みの情報は [`sm_ctrl_last_window`] で取る。
//
// 戻り値: 0=OK、-1=未初期化、-3=未知ノード、-4=CASE 開始失敗、-5=引数不正
// (passcode が仕様の禁止値)、-6=RNG 失敗、-10=busy。
//
// [`SM_CTRL_EV_WINDOW_OPENED`]: sm_ctrl_event_kind_t::SM_CTRL_EV_WINDOW_OPENED
// [`SM_CTRL_EV_WINDOW_FAILED`]: sm_ctrl_event_kind_t::SM_CTRL_EV_WINDOW_FAILED
int32_t sm_ctrl_open_commissioning_window(uint64_t node_id,
                                          uint16_t timeout_s,
                                          uint16_t discriminator,
                                          uint32_t passcode,
                                          uint64_t now_ms);

// 直近に開いた窓の払い出し情報(manual code / QR 文字列込み)を `out` に書く(§17.3)。
//
// 一度も窓を開いていなければ false(`out` は触らない)。窓が期限切れ / Revoke で
// 閉じたかどうかは追跡しない(WindowStatus は
// `sm_ctrl_read_scalar(node, 0, 0x003C, 0x0000)` で読む。0=閉 1=ECM 2=BC)。
bool sm_ctrl_last_window(sm_ctrl_window_t *out);

// 開いているコミッショニング窓を閉じる(0x003C/0x02 RevokeCommissioning、timed invoke)。
//
// 完了は通常の invoke と同じ INVOKE_DONE / INVOKE_FAILED(`node_id` で識別。窓が開いて
// いなければ `status` にクラスタ固有 WindowNotOpen=4)。
// 戻り値: 0=OK、-1=未初期化、-3=未知ノード、-4=CASE 開始失敗、-10=busy。
int32_t sm_ctrl_revoke_commissioning(uint64_t node_id,
                                     uint64_t now_ms);

// ノードの購読をローカルで破棄する(§16.2)。戻り値 = 破棄した本数。
//
// デバイスへは何も送らない(相手側の購読は keep-alive 途絶で自然消滅する)。以降その
// ノードのレポートは捨てられ、SM_CTRL_EV_SUBSCRIPTION_LOST も上がらない。
int32_t sm_ctrl_unsubscribe(uint64_t node_id);

// ノードの購読が生きていれば true(UI 表示・poll 抑止の判定用。§16.2)。
bool sm_ctrl_is_subscribed(uint64_t node_id);

// コントローラ側の各プール使用量を `out` に書く(診断用。未初期化・NULL は 0 埋め)。
//
// デバイス側 [`sm_pool_stats`](crate::sm_pool_stats) と同じ構造体を使う。コントローラの
// IM client は同時トランザクション 1 本固定なので `reads` は 0/1、ハンドシェイク欄は
// 常に 0(SC initiator は slot プールを持たない)。`subs` はコア client の購読数で、
// シムのテーブル([`sm_ctrl_is_subscribed`])と食い違っていないかの確認に使う(§16.6)。
void sm_ctrl_pool_stats(sm_pool_stats_t *out);

// operational(`_matter._tcp`)解決クエリを生成する(§11.1)。戻り値 = クエリ長(0 = 失敗)。
//
// `at` が非 NULL のときはそのアドレス(QU ユニキャスト直指定 = `--at` 相当)へ、NULL なら
// mDNS マルチキャストへ。宛先ポートは常に 5353 に上書きする。C++ は返ったバイト列を
// `tx_dst` 宛に mDNS ソケットで送り、応答を [`sm_ctrl_mdns_rx`] へ給餌する。
size_t sm_ctrl_resolve_start(uint64_t node_id,
                             const sm_addr_t *at,
                             uint64_t _now_ms,
                             uint8_t *tx_out,
                             size_t tx_cap,
                             sm_addr_t *tx_dst);

// mDNS 応答を給餌して operational アドレスを解決する。戻り値: 0=解決、-1=未初期化/NULL、-2=不一致。
//
// 既知ノード(ノード帳)の運用アドレスを更新し、成功時に RESOLVE_DONE イベントを立てる。
int32_t sm_ctrl_mdns_rx(const uint8_t *pkt,
                        size_t len,
                        const sm_addr_t *_src,
                        uint64_t now_ms);

// 既知ノードの現在の運用アドレスを取得する。戻り値 = ノードが存在するか。
bool sm_ctrl_node_addr(uint64_t node_id,
                       sm_addr_t *out);

// 既知ノードの運用アドレスを直接設定する(Thread/SRP 等、mDNS 以外の解決経路用)。
//
// Thread では運用アドレス解決が mDNS ではなく SRP(ボーダー/ハブ自身が SRP サーバ)に
// なるため、C++ 側が `otSrpServerGetNextHost()` 列挙などで得たアドレスをノード帳へ
// 反映するための入口(F8b、docs/design/p4-thread-controller.md §3)。
// 内部処理は [`sm_ctrl_mdns_rx`] の解決成功時と同じ(ノード帳更新 + RESOLVE_DONE)。
//
// 戻り値: 0=OK、-1=未初期化/NULL、-2=ノード帳に `node_id` なし。
int32_t sm_ctrl_set_node_addr(uint64_t node_id,
                              const sm_addr_t *addr);

// 進行中の運用操作を外部都合で中断し Idle に戻す(C++ の待ちがタイムアウトしたとき用)。
//
// 不達ノード宛の CASE は initiator の HANDSHAKE_TIMEOUT(60s)まで内部で粘り、
// その間の全操作が busy(-10)で弾かれる(T5 実機)。ハンドシェイクスロット・予約
// セッション・exchange は [`ControllerStack::abort_handshake`] で解放する。
// 応答待ち中(AwaitOp)の IM トランザクションは [`ControllerStack::abort_op`] で畳み、
// exchange を即時回収する(「MRP の諦めで自然解放」は要求が standalone ACK 済みだと
// 成り立たず、exchange が永久に残る — 実機 2026-08-25 の「両デバイス不達」の真因)。
//
// 戻り値: 1=中断した、0=元々 Idle、-1=未初期化。
int32_t sm_ctrl_abort_op(void);

// 現在の管理ノード数(ノード帳のエントリ数)。
size_t sm_ctrl_node_count(void);

// commissionable 広告の service data(0xFFF6、8 バイト)から discriminator を照合する(§11.4)。
//
// `svc_data` は BlueZ/NimBLE が届ける 0xFFF6 service data payload(先頭 8 バイトを使う)。
// 一致で `true`。ble 無効ビルドは常に `false`。初期化不要(純関数)。
bool sm_ctrl_match_adv(const uint8_t *svc_data,
                       size_t len,
                       uint16_t discriminator);

// BLE(BTP)コミッショニングを開始する(§11.4)。
//
// `kind`: 0=WiFi(`cred1`=SSID、`cred2`=パスフレーズ)、1=Thread(`cred1`=dataset TLV、
// `cred2` 未使用)。AddNOC 後にネットワーク資格情報を投入し ConnectNetwork まで BTP 上で
// 進め、CASE 直前で保留して [`SM_CTRL_EV_BLE_DONE`] を立てる(以降 §11.4 の handoff)。
//
// 呼び出し前に C++ は scan([`sm_ctrl_match_adv`])→ connect 済みであること。以降
// CONNECTED/C2_SUBSCRIBED/C2_INDICATION を [`sm_ctrl_ble_event`] で、C1 write を
// [`sm_ctrl_ble_poll`] で給餌する。
//
// 戻り値: 0=OK、-1=未初期化/ble 無効、-2=busy、-3=資格情報不正、-4=commission 拒否。
int32_t sm_ctrl_ble_pair_start(uint64_t node_id,
                               uint32_t passcode,
                               uint8_t kind,
                               const uint8_t *cred1,
                               size_t cred1_len,
                               const uint8_t *cred2,
                               size_t cred2_len,
                               uint64_t now_ms);

// BLE central のイベントを給餌する(§11.4)。デバイス側 [`sm_ble_event`] の鏡像。
//
// - `SM_BLE_CONNECTED`(arg=ATT MTU): BTP handshake を能動開始する(Capabilities Request は
//   `sm_ctrl_ble_poll` が排出する)。
// - `SM_BLE_C2_SUBSCRIBED`: C2 indication の購読完了(central 自身の購読状態)。
// - `SM_BLE_C2_INDICATION`(= `SM_BLE_C1_WRITE` の ABI 値を流用): 受信 1 フラグメント。
// - `SM_BLE_DISCONNECTED`: 切断。BTP をリセットする(handoff は継続)。
//
// 戻り値: 0=OK、-1=未初期化/NULL/ble 無効、-2=2 本目の接続拒否、-3=BTP 給餌失敗。
int32_t sm_ctrl_ble_event(sm_ble_event_kind_t kind,
                          uint16_t arg,
                          const uint8_t *data,
                          size_t len,
                          uint64_t now_ms);

// C1 write で送るべき次の BTP フラグメントを取り出す(§11.4)。0 = なし。
//
// 最初に handshake request(Capabilities Request)を、以降は `process_outgoing` の
// データセグメント / standalone ACK を排出する。C++ は 0 になるまで呼んで C1 write する。
// BTP の再送・keep-alive ACK もここから産まれる。ble 無効ビルドは常に 0。
size_t sm_ctrl_ble_poll(uint64_t now_ms,
                        uint8_t *frag_out,
                        size_t cap);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus

#endif /* SIMPLE_MATTER_H */
